/**
 *
 * Author: Pierre Dahmani
 * Created: 06.01.2022
 *
 * Description: All weather specific type definitions which don't come fromt he
 * autogenerated quicktype weather api.
 */

export enum WeatherBoxType {
    // first box which is shown on top. NOTE(pierre): this might be removed if
    // it will not be needed.
    Main,
    // each hourly box which is shown in a series
    Hourly,
    // each daily box which is shown in a series
    Daily,
}

export enum WeatherBoxCount {
    // 48 is maximum for hours when using the free onecall api.
    Hourly = 10,
    // 7 is maximum for days when using the free onecall api. src:
    // https://openweathermap.org/api/one-call-api
    Daily = 7,
}

export enum WeatherUnits {
    Imperial = "imperial",
    Metric = "metric",
}

export enum TemperatureUnits {
    Imperial = "°F",
    Metric = "°C",
}

export enum WindUnits {
    Imperial = "mph",
    Metric = "km/h",
}
